import { User, Faculty, TimetableEntry, SubstitutionDuty, DashboardStats } from '../types';

export const INSTITUTIONAL_USERS: Record<string, { user: User; token: string }> = {
  'admin@institution.edu': {
    token: 'mock_jwt_token_admin',
    user: {
      id: 1,
      email: 'admin@institution.edu',
      full_name: 'System Administrator',
      is_active: true,
      role: {
        id: 1,
        name: 'ADMIN',
        description: 'System Administrator with full access',
        is_default_exempt: true,
        is_default_eligible: false,
        permissions: ['all'],
      },
      faculty_id: 1,
      faculty_code: 'ADMIN-01',
      department_name: 'Information Technology & Administration',
    },
  },
  'hod.cse@institution.edu': {
    token: 'mock_jwt_token_hod_cse',
    user: {
      id: 2,
      email: 'hod.cse@institution.edu',
      full_name: 'Dr. Sunita Rao',
      is_active: true,
      role: {
        id: 3,
        name: 'HOD',
        description: 'Head of Department (CSE)',
        is_default_exempt: true,
        is_default_eligible: false,
        permissions: ['view_dashboard', 'view_department', 'view_reports', 'manage_substitutions'],
      },
      faculty_id: 2,
      faculty_code: 'FAC-002',
      department_name: 'Computer Science & Engineering',
    },
  },
  'dean@institution.edu': {
    token: 'mock_jwt_token_dean',
    user: {
      id: 3,
      email: 'dean@institution.edu',
      full_name: 'Dr. Vikram Malhotra',
      is_active: true,
      role: {
        id: 2,
        name: 'DEAN',
        description: 'Dean of Academic Affairs',
        is_default_exempt: true,
        is_default_eligible: false,
        permissions: ['view_dashboard', 'view_reports', 'view_timetables', 'compliance_audit'],
      },
      faculty_id: 3,
      faculty_code: 'FAC-001',
      department_name: 'Academic Affairs & Governance',
    },
  },
  'kumar@institution.edu': {
    token: 'mock_jwt_token_faculty',
    user: {
      id: 4,
      email: 'kumar@institution.edu',
      full_name: 'Prof. Kumar Sanjeev',
      is_active: true,
      role: {
        id: 4,
        name: 'FACULTY',
        description: 'Teaching Faculty Member',
        is_default_exempt: false,
        is_default_eligible: true,
        permissions: ['view_my_schedule', 'view_my_duties', 'apply_leave'],
      },
      faculty_id: 6,
      faculty_code: 'FAC-101',
      department_name: 'Computer Science & Engineering',
    },
  },
};

export const MOCK_FACULTY_LIST: Faculty[] = [
  {
    id: 6,
    faculty_id: 'FAC-101',
    user_id: 4,
    name: 'Prof. Kumar Sanjeev',
    email: 'kumar@institution.edu',
    phone: '+91 98765 43210',
    department_id: 1,
    department_code: 'CSE',
    department_name: 'Computer Science & Engineering',
    designation: 'Associate Professor',
    role_id: 4,
    role_name: 'FACULTY',
    is_substitution_eligible: true,
    is_exempt: false,
    max_weekly_substitutions: 4,
    subject_expertise: ['CS101', 'CS103'],
    status: 'ACTIVE',
    weekly_substitution_count: 2,
    today_regular_classes_count: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    faculty_id: 'FAC-102',
    user_id: 5,
    name: 'Prof. Ravi Shankar',
    email: 'ravi@institution.edu',
    phone: '+91 98765 43211',
    department_id: 1,
    department_code: 'CSE',
    department_name: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    role_id: 4,
    role_name: 'FACULTY',
    is_substitution_eligible: true,
    is_exempt: false,
    max_weekly_substitutions: 4,
    subject_expertise: ['CS101', 'CS104'],
    status: 'ACTIVE',
    weekly_substitution_count: 1,
    today_regular_classes_count: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    faculty_id: 'FAC-103',
    user_id: 6,
    name: 'Prof. Ahmed Khan',
    email: 'ahmed@institution.edu',
    phone: '+91 98765 43212',
    department_id: 1,
    department_code: 'CSE',
    department_name: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    role_id: 4,
    role_name: 'FACULTY',
    is_substitution_eligible: true,
    is_exempt: false,
    max_weekly_substitutions: 4,
    subject_expertise: ['CS102', 'CS103'],
    status: 'ACTIVE',
    weekly_substitution_count: 3,
    today_regular_classes_count: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 9,
    faculty_id: 'FAC-104',
    user_id: 7,
    name: 'Prof. Priya Nair',
    email: 'priya@institution.edu',
    phone: '+91 98765 43213',
    department_id: 1,
    department_code: 'CSE',
    department_name: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    role_id: 4,
    role_name: 'FACULTY',
    is_substitution_eligible: true,
    is_exempt: false,
    max_weekly_substitutions: 4,
    subject_expertise: ['CS104', 'CS105'],
    status: 'ACTIVE',
    weekly_substitution_count: 0,
    today_regular_classes_count: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    faculty_id: 'FAC-002',
    user_id: 2,
    name: 'Dr. Sunita Rao',
    email: 'hod.cse@institution.edu',
    phone: '+91 98765 43202',
    department_id: 1,
    department_code: 'CSE',
    department_name: 'Computer Science & Engineering',
    designation: 'Professor & HOD',
    role_id: 3,
    role_name: 'HOD',
    is_substitution_eligible: false,
    is_exempt: true,
    max_weekly_substitutions: 0,
    subject_expertise: ['CS102', 'CS103'],
    status: 'ACTIVE',
    weekly_substitution_count: 0,
    today_regular_classes_count: 1,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  today_date: new Date().toISOString().split('T')[0],
  total_faculty: 25,
  active_faculty: 23,
  today_absences_count: 2,
  today_affected_classes_count: 4,
  today_allocated_count: 3,
  today_unallocated_count: 1,
  weekly_total_substitutions: 14,
  faculty_at_limit_count: 2,
  faculty_near_limit_count: 5,
  duty_distribution: { '0 duties': 10, '1 duty': 8, '2 duties': 4, '3 duties': 2, '4 duties': 1 },
  recent_activities: [],
  system_alerts: [],
};

export const MOCK_TIMETABLE_ENTRIES: TimetableEntry[] = [
  {
    id: 101,
    timetable_version_id: 1,
    faculty_id: 6,
    faculty_name: 'Prof. Kumar Sanjeev',
    class_section_id: 1,
    class_name: 'CSE-3A',
    subject_id: 1,
    subject_code: 'CS101',
    subject_name: 'Data Structures & Algorithms',
    day_of_week: new Date().getDay() === 0 ? 6 : new Date().getDay() - 1,
    start_time: '09:00',
    end_time: '09:50',
    room_number: 'LH-101',
  },
  {
    id: 102,
    timetable_version_id: 1,
    faculty_id: 6,
    faculty_name: 'Prof. Kumar Sanjeev',
    class_section_id: 2,
    class_name: 'CSE-3B',
    subject_id: 2,
    subject_code: 'CS103',
    subject_name: 'Operating Systems',
    day_of_week: new Date().getDay() === 0 ? 6 : new Date().getDay() - 1,
    start_time: '11:00',
    end_time: '11:50',
    room_number: 'LH-103',
  },
  {
    id: 103,
    timetable_version_id: 1,
    faculty_id: 7,
    faculty_name: 'Prof. Ravi Shankar',
    class_section_id: 1,
    class_name: 'CSE-3A',
    subject_id: 3,
    subject_code: 'CS104',
    subject_name: 'Computer Networks',
    day_of_week: new Date().getDay() === 0 ? 6 : new Date().getDay() - 1,
    start_time: '10:00',
    end_time: '10:50',
    room_number: 'LH-102',
  },
];

export const MOCK_DUTIES: SubstitutionDuty[] = [
  {
    id: 1,
    requirement_id: 1,
    date: new Date().toISOString().split('T')[0],
    day_of_week: 1,
    period_start: '12:00',
    period_end: '12:50',
    class_section_id: 1,
    class_name: 'CSE-4A',
    subject_id: 2,
    subject_code: 'CS102',
    subject_name: 'Database Management Systems',
    original_faculty_id: 8,
    original_faculty_name: 'Prof. Ahmed Khan',
    assigned_faculty_id: 6,
    assigned_faculty_name: 'Prof. Kumar Sanjeev',
    assigned_faculty_code: 'FAC-101',
    allocation_method: 'ALGORITHM',
    status: 'SCHEDULED',
    weekly_count_at_assignment: 2,
    daily_classes_at_assignment: 2,
    is_manual_override: false,
    allocation_reason: 'Matched subject expertise (CS102) • Weekly duty load within limit (2/4) • Zero consecutive period clash.',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    requirement_id: 2,
    date: new Date().toISOString().split('T')[0],
    day_of_week: 1,
    period_start: '14:00',
    period_end: '14:50',
    class_section_id: 2,
    class_name: 'CSE-2B',
    subject_id: 1,
    subject_code: 'CS101',
    subject_name: 'Data Structures Lab',
    original_faculty_id: 9,
    original_faculty_name: 'Prof. Priya Nair',
    assigned_faculty_id: 7,
    assigned_faculty_name: 'Prof. Ravi Shankar',
    assigned_faculty_code: 'FAC-102',
    allocation_method: 'ALGORITHM',
    status: 'SCHEDULED',
    weekly_count_at_assignment: 1,
    daily_classes_at_assignment: 1,
    is_manual_override: false,
    allocation_reason: 'Direct subject domain match • Period free in timetable • Workload balanced (1/4 this week).',
    created_at: new Date().toISOString(),
  },
];
